#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := ardupilot_obstacle_avoidance

include $(IDF_PATH)/make/project.mk

